"""initial schema

Revision ID: 0b2e72e9d569
Revises: 
Create Date: 2026-05-11 17:13:14.961195+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0b2e72e9d569'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_user_id', sa.BigInteger(), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=True),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('added_by', sa.Integer(), nullable=True),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("role IN ('super', 'sub')", name='ck_admins_role'),
    sa.ForeignKeyConstraint(['added_by'], ['admins.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admins_telegram_user_id'), ['telegram_user_id'], unique=True)
        batch_op.create_index('uq_one_super_admin', ['role'], unique=True, postgresql_where=sa.text("role = 'super'"), sqlite_where=sa.text("role = 'super'"))

    op.create_table('groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_chat_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_groups_telegram_chat_id'), ['telegram_chat_id'], unique=True)

    op.create_table('recovery_key_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key_hash_attempted', sa.String(length=256), nullable=True),
    sa.Column('attempted_by_telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('result', sa.String(length=32), nullable=False),
    sa.Column('attempted_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recovery_key_attempts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recovery_key_attempts_attempted_at'), ['attempted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_recovery_key_attempts_attempted_by_telegram_id'), ['attempted_by_telegram_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_recovery_key_attempts_result'), ['result'], unique=False)

    op.create_table('recovery_reset_throttle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_user_id', sa.BigInteger(), nullable=False),
    sa.Column('last_reset_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recovery_reset_throttle', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recovery_reset_throttle_telegram_user_id'), ['telegram_user_id'], unique=True)

    op.create_table('settings',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('blacklist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_user_id', sa.BigInteger(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('added_by', sa.Integer(), nullable=True),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['added_by'], ['admins.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('blacklist', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_blacklist_telegram_user_id'), ['telegram_user_id'], unique=True)

    op.create_table('inviters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_user_id', sa.BigInteger(), nullable=True),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('group_label', sa.String(length=64), nullable=False),
    sa.Column('target_group_id', sa.Integer(), nullable=False),
    sa.Column('required_materials', sa.JSON(), nullable=False),
    sa.Column('review_mode', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("review_mode IN ('self', 'admin_delegated')", name='ck_inviters_review_mode'),
    sa.ForeignKeyConstraint(['target_group_id'], ['groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inviters', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inviters_telegram_user_id'), ['telegram_user_id'], unique=False)

    op.create_table('applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('applicant_telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('applicant_username', sa.String(length=64), nullable=True),
    sa.Column('applicant_display_name', sa.String(length=256), nullable=True),
    sa.Column('inviter_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('wizard_step', sa.Integer(), nullable=False),
    sa.Column('reject_reason', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_by_type', sa.String(length=16), nullable=True),
    sa.Column('reviewed_by_id', sa.BigInteger(), nullable=True),
    sa.Column('locked_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("reviewed_by_type IS NULL OR reviewed_by_type IN ('inviter', 'admin')", name='ck_applications_reviewed_by_type'),
    sa.CheckConstraint("status IN ('wizard', 'pending', 'approved', 'rejected', 'cancelled')", name='ck_applications_status'),
    sa.ForeignKeyConstraint(['inviter_id'], ['inviters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_applications_applicant_telegram_id'), ['applicant_telegram_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_applications_inviter_id'), ['inviter_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_applications_status'), ['status'], unique=False)

    op.create_table('application_materials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('material_type', sa.String(length=32), nullable=False),
    sa.Column('content_type', sa.String(length=16), nullable=False),
    sa.Column('telegram_file_id', sa.String(length=256), nullable=True),
    sa.Column('text_content', sa.Text(), nullable=True),
    sa.Column('original_message_id', sa.BigInteger(), nullable=False),
    sa.Column('media_group_seq', sa.Integer(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("content_type IN ('photo', 'text')", name='ck_app_materials_content_type'),
    sa.CheckConstraint("material_type IN ('约课记录', '上课手势', '出击报告')", name='ck_app_materials_type'),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('application_materials', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_application_materials_application_id'), ['application_id'], unique=False)

    op.create_table('attack_report_forwards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.BigInteger(), nullable=True),
    sa.Column('telegram_message_id', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('forwarded_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.CheckConstraint("status IN ('sent', 'failed', 'skipped_no_report', 'skipped_no_channel')", name='ck_arf_status'),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('attack_report_forwards', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attack_report_forwards_application_id'), ['application_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attack_report_forwards_status'), ['status'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_telegram_id', sa.BigInteger(), nullable=True),
    sa.Column('actor_role', sa.String(length=32), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('target_application_id', sa.Integer(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['target_application_id'], ['applications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_actor_telegram_id'), ['actor_telegram_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_created_at'), ['created_at'], unique=False)

    op.create_table('invite_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('invite_link', sa.String(length=256), nullable=False),
    sa.Column('invite_link_name', sa.String(length=64), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('expire_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('used_by_telegram_id', sa.BigInteger(), nullable=True),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_anomaly', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('invite_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invite_links_application_id'), ['application_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invite_links_invite_link_name'), ['invite_link_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_invite_links_is_used'), ['is_used'], unique=False)

    op.create_table('recovery_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('owner_telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('original_owner_telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('key_hash', sa.String(length=256), nullable=False),
    sa.Column('key_prefix', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('used_by_telegram_id', sa.BigInteger(), nullable=True),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('previous_key_id', sa.Integer(), nullable=True),
    sa.Column('failed_attempts', sa.Integer(), nullable=False),
    sa.Column('cleanup_action', sa.String(length=32), nullable=True),
    sa.Column('cleanup_old_account_status', sa.String(length=16), nullable=True),
    sa.Column('cleanup_executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('active', 'used', 'revoked', 'reset')", name='ck_recovery_keys_status'),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.ForeignKeyConstraint(['previous_key_id'], ['recovery_keys.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_hash')
    )
    with op.batch_alter_table('recovery_keys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recovery_keys_application_id'), ['application_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_recovery_keys_owner_telegram_id'), ['owner_telegram_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_recovery_keys_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recovery_keys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recovery_keys_status'))
        batch_op.drop_index(batch_op.f('ix_recovery_keys_owner_telegram_id'))
        batch_op.drop_index(batch_op.f('ix_recovery_keys_application_id'))

    op.drop_table('recovery_keys')
    with op.batch_alter_table('invite_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invite_links_is_used'))
        batch_op.drop_index(batch_op.f('ix_invite_links_invite_link_name'))
        batch_op.drop_index(batch_op.f('ix_invite_links_application_id'))

    op.drop_table('invite_links')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_created_at'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_actor_telegram_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('attack_report_forwards', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attack_report_forwards_status'))
        batch_op.drop_index(batch_op.f('ix_attack_report_forwards_application_id'))

    op.drop_table('attack_report_forwards')
    with op.batch_alter_table('application_materials', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_application_materials_application_id'))

    op.drop_table('application_materials')
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_applications_status'))
        batch_op.drop_index(batch_op.f('ix_applications_inviter_id'))
        batch_op.drop_index(batch_op.f('ix_applications_applicant_telegram_id'))

    op.drop_table('applications')
    with op.batch_alter_table('inviters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inviters_telegram_user_id'))

    op.drop_table('inviters')
    with op.batch_alter_table('blacklist', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_blacklist_telegram_user_id'))

    op.drop_table('blacklist')
    op.drop_table('settings')
    with op.batch_alter_table('recovery_reset_throttle', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recovery_reset_throttle_telegram_user_id'))

    op.drop_table('recovery_reset_throttle')
    with op.batch_alter_table('recovery_key_attempts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recovery_key_attempts_result'))
        batch_op.drop_index(batch_op.f('ix_recovery_key_attempts_attempted_by_telegram_id'))
        batch_op.drop_index(batch_op.f('ix_recovery_key_attempts_attempted_at'))

    op.drop_table('recovery_key_attempts')
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_groups_telegram_chat_id'))

    op.drop_table('groups')
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.drop_index('uq_one_super_admin', postgresql_where=sa.text("role = 'super'"), sqlite_where=sa.text("role = 'super'"))
        batch_op.drop_index(batch_op.f('ix_admins_telegram_user_id'))

    op.drop_table('admins')
    # ### end Alembic commands ###
