"""add invite_links.expired_notified_at

Revision ID: a12e60b65f50
Revises: 1b5ff38740dd
Create Date: 2026-05-11 17:48:41.579431+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a12e60b65f50'
down_revision: Union[str, None] = '1b5ff38740dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invite_links', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expired_notified_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invite_links', schema=None) as batch_op:
        batch_op.drop_column('expired_notified_at')

    # ### end Alembic commands ###
