"""add reimbursement tables

Revision ID: 0dfedbea360e
Revises: a12e60b65f50
Create Date: 2026-05-11 19:08:26.992657+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0dfedbea360e'
down_revision: Union[str, None] = 'a12e60b65f50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eligibility_chats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_chat_id', sa.BigInteger(), nullable=False),
    sa.Column('chat_type', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("chat_type IN ('group', 'supergroup', 'channel')", name='ck_elig_chat_type'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('eligibility_chats', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_eligibility_chats_telegram_chat_id'), ['telegram_chat_id'], unique=True)

    op.create_table('reimbursement_user_overrides',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_user_id', sa.BigInteger(), nullable=False),
    sa.Column('cooldown_days', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('added_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['added_by'], ['admins.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reimbursement_user_overrides', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reimbursement_user_overrides_telegram_user_id'), ['telegram_user_id'], unique=True)

    op.create_table('reimbursement_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('applicant_telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('applicant_username', sa.String(length=64), nullable=True),
    sa.Column('applicant_display_name', sa.String(length=256), nullable=True),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('wizard_step', sa.Integer(), nullable=False),
    sa.Column('reject_reason', sa.Text(), nullable=True),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_by_telegram_id', sa.BigInteger(), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('paid_by_telegram_id', sa.BigInteger(), nullable=True),
    sa.Column('alipay_code_text', sa.Text(), nullable=True),
    sa.Column('locked_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("status IN ('wizard', 'pending', 'approved', 'rejected', 'cancelled', 'paid')", name='ck_rei_status'),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reimbursement_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reimbursement_requests_applicant_telegram_id'), ['applicant_telegram_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reimbursement_requests_application_id'), ['application_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reimbursement_requests_status'), ['status'], unique=False)

    op.create_table('reimbursement_audit_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reimbursement_id', sa.Integer(), nullable=False),
    sa.Column('reviewer_telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('media_message_id', sa.BigInteger(), nullable=True),
    sa.Column('text_message_id', sa.BigInteger(), nullable=False),
    sa.Column('report_message_id', sa.BigInteger(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['reimbursement_id'], ['reimbursement_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reimbursement_audit_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reimbursement_audit_messages_reimbursement_id'), ['reimbursement_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reimbursement_audit_messages_reviewer_telegram_id'), ['reviewer_telegram_id'], unique=False)

    op.create_table('reimbursement_materials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reimbursement_id', sa.Integer(), nullable=False),
    sa.Column('material_type', sa.String(length=32), nullable=False),
    sa.Column('content_type', sa.String(length=16), nullable=False),
    sa.Column('telegram_file_id', sa.String(length=256), nullable=True),
    sa.Column('text_content', sa.Text(), nullable=True),
    sa.Column('original_message_id', sa.BigInteger(), nullable=False),
    sa.Column('media_group_seq', sa.Integer(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("content_type IN ('photo', 'text')", name='ck_rei_mat_content_type'),
    sa.CheckConstraint("material_type IN ('约课记录', '上课手势', '出击报告')", name='ck_rei_mat_type'),
    sa.ForeignKeyConstraint(['reimbursement_id'], ['reimbursement_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reimbursement_materials', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reimbursement_materials_reimbursement_id'), ['reimbursement_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reimbursement_materials', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reimbursement_materials_reimbursement_id'))

    op.drop_table('reimbursement_materials')
    with op.batch_alter_table('reimbursement_audit_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reimbursement_audit_messages_reviewer_telegram_id'))
        batch_op.drop_index(batch_op.f('ix_reimbursement_audit_messages_reimbursement_id'))

    op.drop_table('reimbursement_audit_messages')
    with op.batch_alter_table('reimbursement_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reimbursement_requests_status'))
        batch_op.drop_index(batch_op.f('ix_reimbursement_requests_application_id'))
        batch_op.drop_index(batch_op.f('ix_reimbursement_requests_applicant_telegram_id'))

    op.drop_table('reimbursement_requests')
    with op.batch_alter_table('reimbursement_user_overrides', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reimbursement_user_overrides_telegram_user_id'))

    op.drop_table('reimbursement_user_overrides')
    with op.batch_alter_table('eligibility_chats', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_eligibility_chats_telegram_chat_id'))

    op.drop_table('eligibility_chats')
    # ### end Alembic commands ###
