"""add audit_messages table

Revision ID: 1b5ff38740dd
Revises: 0b2e72e9d569
Create Date: 2026-05-11 17:30:40.847116+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '1b5ff38740dd'
down_revision: Union[str, None] = '0b2e72e9d569'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('reviewer_telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('media_message_id', sa.BigInteger(), nullable=True),
    sa.Column('text_message_id', sa.BigInteger(), nullable=False),
    sa.Column('report_message_id', sa.BigInteger(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_messages_application_id'), ['application_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_messages_reviewer_telegram_id'), ['reviewer_telegram_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_messages_reviewer_telegram_id'))
        batch_op.drop_index(batch_op.f('ix_audit_messages_application_id'))

    op.drop_table('audit_messages')
    # ### end Alembic commands ###
